services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - hauvas-redis:/data
    restart: unless-stopped

volumes:
  hauvas-redis:
