# Generated by Django 5.0.6 on 2024-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_city_profile_country_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
