# Generated by Django 5.0.6 on 2024-07-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_announcement_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
