# Generated by Django 5.0.6 on 2024-07-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_modulelist_moduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleitem',
            name='short_description',
            field=models.CharField(default='Learn the {your explanation about the course}!', max_length=254),
        ),
        migrations.AlterField(
            model_name='moduleitem',
            name='description',
            field=models.TextField(default='Put your description here about the module, and even content'),
        ),
    ]
