# Generated by Django 5.0.6 on 2024-07-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_alter_course_department_alter_course_professor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_codename',
            new_name='codename',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_syllabus',
            new_name='syllabus',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_unit',
            new_name='unit',
        ),
    ]
