# Generated by Django 5.0.6 on 2024-07-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0005_alter_professor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.TextField(default='This is about course, populate it later'),
        ),
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.TextField(default='This is syllabus course, populate it later'),
        ),
    ]
